- name: Deploy application stack
  hosts: all
  become: true

  tasks:
    - name: Update and upgrade apt packages
      apt:
        update_cache: yes
        upgrade: dist

    - name: Install OpenJDK 17
      apt:
        name: openjdk-17-jre
        state: present

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install Docker Compose
      become: yes
      get_url:
        url: "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)"
        dest: /usr/local/bin/docker-compose
        mode: 'u+x'

    - name: Copy Docker Compose file to server
      copy:
        src: ./docker-compose.yml
        dest: /opt/artstyle/docker-compose.yml

    - name: Verify Docker installation
      command: docker --version

    - name: Verify Docker Compose installation
      command: docker-compose --version

    # - name: Ensure .env file exists
    #   copy:
    #     src: ./artstyle.env
    #     dest: /opt/artstyle/.env

    # - name: Start application stack
    #   command: docker-compose -f /opt/artstyle/docker-compose.yml up -d

  # tasks:

  #   - name: Install required dependencies for Docker
  #     apt:
  #       name:
  #         - apt-transport-https
  #         - ca-certificates
  #         - curl
  #         - software-properties-common
  #       state: present

  #   - name: Add Docker's official GPG key
  #     command: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -

  #   - name: Add Docker repository
  #     apt_repository:
  #       repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable'
  #       state: present

  #   - name: Install Docker
  #     apt:
  #       name: docker-ce
  #       state: latest

  #   - name: Start and enable Docker service
  #     service:
  #       name: docker
  #       state: started
  #       enabled: true
